### ISSUE TITLE
Can't resolve com.github.mvallerie#sbt-scage-plugin;0.1-SNAPSHOT

### ISSUE THREAD

**Issue by vpong** [mvallerie/sbt-scage-plugin#3]
I've been trying to a while to get this plug, but I keep getting the following error:

    [error] (*:update) sbt.ResolveException: unresolved dependency: com.github.mvallerie#sbt-scage-plugin;0.1-SNAPSHOT: not found

My project/plugins.sbt:

    resolvers += Resolver.url("sbt-plugin-snapshots", new URL("http://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/"))(Resolver.ivyStylePatterns)
    addSbtPlugin("com.github.mvallerie" % "sbt-scage-plugin" % "0.1-SNAPSHOT")

My build.sbt:

    lazy val root = (project in file(".")).                                          
      settings(                                                                      
        name := "project-name",                                                    
        version := "1.0",                                                            
        scalaVersion := "2.11.6"                                                            
  )

Any ideas on how to resolve this issue? I even tried running the example code in the repo, and I got the same error. Thanks.

**Comment by mvallerie** [comment]
Hey !

Sorry, my mistake. SBT community plugins (including this one) are published there : http://repo.scala-sbt.org/

The point is, this URI was pointing on an artifactory instance, which has been deprecated on May 31th 2015. The URI is now mirroring a Bintray repository, according to http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html

I received an email about that a few months ago, but didn't get the time to manage the transition.

This is now done, i'm just waiting for the approval to get the plugin published on bintray sbt repository, so leaving that open. I'll let you know as soon as it is approved.

You will need to change your `project/plugins.sbt` to : 

    resolvers += Resolver.sbtPluginRepo("releases")
    
    addSbtPlugin("com.github.mvallerie" % "sbt-scage-plugin" % "0.1")

**Comment by mvallerie** [comment]
The plugin has just been approved on Binstray sbt repository. The example project now updates and runs fine on my side, so i'm closing this issue. Let me know if this is not the case on your side.

**Comment by vitchyr** [comment]
Sweet, it works. Thank you!
